[workspace]
members = [
    "command-framework",
    "command-framework-macros",
    "gateway",
    "gateway-client",
    "i18n-rust",
    "module-catching",
    "module-general",
    "module-pokedex",
    "protobuf-rust",
]
