[workspace]
members = [
    "command-framework",
    "command-framework-macros",
    "command-framework-test",
    "gateway",
    "gateway-client",
    "i18n-rust",
    "module-pokedex",
    "protobuf-rust",
]
